server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://kesavan.db.elephantsql.com:5432/koakpaxy
    username: koakpaxy
    password: 98y1eQwX2DMwXYgRdJaNqZH8EdTVFMpg
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
