server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${HOSTNAME_BDD}:5432/${NAME_BDD}
    username: ${USER_BDD}
    password: ${PASSWORD_BDD}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  show-spring-cloud-functions: false