server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    password: ${PASSWORD_BDD}
    url: jdbc:postgresql://${HOSTNAME_BDD}:5432/${NAME_BDD}
    username: ${USER_BDD}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
    show-sql: true
